# -*- coding: utf-8 -*-

# PARA ADICIONAR SIMBOLOS NAO RECONHECIDOS PELO PYTHON USAMOS O CODIGO ANTERIOR
# PODEMOS COMENTAR ASSIM!

print('Olá Mundo!')
# PODEMOS USAR '' OU "" DENTRO DO PRINT
print("Olá Mundo!")
